apiVersion: v1
kind: Service
metadata:
  name: demo-webserver-service
  namespace: demo-webserver
spec:
  selector:
    app: demo-webserver
  ports:
  - port: 3555
    protocol: TCP
    targetPort: 3555
