apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-webserver-deployment
  namespace: demo-webserver
spec:
  selector:
    matchLabels:
      app: demo-webserver
  replicas: 2
  template:
    metadata:
      labels:
        app: demo-webserver
    spec:
      containers:
      - name: demo-webserver
        # For demonstration, change the :state-1 tag to :state-2
        # ArgoCD should manage the new desired state and automatically deploy the new image in edge-cluster
        image: docker.io/dangelic/edgecluster-prototype-dockerhub-registry:state-1
        ports:
        - containerPort: 3555
